module.exports = {
    'C1': false,
    'D♭1': false,
    'D1': false,
    'E♭1': false,
    'E1': false,
    'F1': false,
    'G♭1': false,
    'G1': false,
    'A♭1': false,
    'A1': false,
    'B♭1': false,
    'B1': false,
    'C2': false,
    'D♭2': false,
    'D2': false,
    'E♭2': false,
    'E2': false,
    'F2': false,
    'G♭2': false,
    'G2': false,
    'A♭2': false,
    'A2': false,
    'B♭2': false,
    'B2': false
};